### ISSUE TITLE
Unable to install fresh clone

### ISSUE THREAD

**Issue by jaycle** [pjlast/fsocaml#3]
Thanks for pulling this together. I think this going to be a boon for helping newbies like me trim the decision fatigue for making useful web projects.

I think that this opam pin needs to be "git+https://". At least that was the change required on my system.

https://github.com/pjlast/fsocaml/blob/a1d99e182c6142b79809aa7a5511399a4322e05d/fsocaml.opam#L37

I tried this originally on 4.14 and fixed it with git+https://. Then realized I'd rather be on 5.1.0 and removed my switch and reran `opam install . --deps-only`, (without the "git+" prefix). This worked as expected. So I'm not sure if the prefix was necessary or not, but all docs seem to suggest it should be there.

**Comment by gvrooyen** [comment]
I ran into this issue too and can confirm that @jaycle's `git+https://` change fixed it for me.

**Comment by pjlast** [comment]
Thanks @jaycle and @gvrooyen ! There were actually quite a few dependencies missing. I added them all and tested with a local opam switch instead of using the global one.
